sudo: required
dist: xenial
language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm run lint
deploy:
  provider: npm
  email: tech@io.builders
  api_key:
    secure: yR7Id4i6uK/OdSuKh9I/SaGk/cCRh3OzpAYXez4JPM4Nx0vFqGcolnFw77xMaaiTZ/C/tr2crQdYWU4zaBYUyFuzz2epmnaO0UAOj/Z21VYmeFvFYpfCIXFW+gnvkGj8UeOMqzhl1cHye63PgGCAOnQ4Z+D3AJvRKTpTQ44I74JZ3qm7eZZP9sKDkCx931ptfQCgM+zmXrU0e9j6ljbUrujoO5q1Oai3R1yu3pYlcLWyTNUxzDXnWvHYfQeNgqGdhvLOF5K06Nehv88kAOhiWdxC0r9gGklQ9GEG8AxaUZqalOkdLTVfqKvqyUfwF3tWedlOGLNkpnT8AzH8Lnpy87j3jLcGENaToBGai3w0KSBb0u6sqviqEspd7rC5M16D3ZItyoXZMchyC2jOGhHuXJLLYqq6MALnjSStIv1+qaEVuP5oFhG5OyrdZJ3NqdzGdBt9X+7LCbnpvNZrgTcm+Pkd90z+eiuDo2BclNkX8x+RAZQ6665bjUChQeCrg2K+OS9oNw2Irlcq5XyCABsLYEgU+2OInWyfNt17SWPwgmqKjtdZEtte8gq9NVEkcBpnIWsdDRqP9CTKqQoh+B1ZiDdG6GRI+ntSEIWZ06hNpW6UD0Hiyo1PLqttIxr5l1dsxLFWbiu9zcUKAtc4ftJ8de5l+4ORizlX78hPIaOWVaE=
  on:
    tags: true
    branch: master
    repo: IoBuilders/truffle-ganache-test
